### ISSUE TITLE
Bug in decryption first bytes in CBC mode

### ISSUE THREAD

**Issue by itaymigdal** [jangko/nimAES#11]
Hey :)
I encountered a bug in CBC mode - tried to encrypt and decrypt a string, but seems like the first bytes are not decrypted well.
the code:

```
import nimAES

let communication_aes_key = "ieMhfhf!!56=z$V4fd*3t15f3.3ZZaw3"
let communication_aes_iv = "-+x3BBw3NN_=!s32"

proc encrypt_cbc(plain_text: string): string =
    var aes = initAES()
    if aes.setEncodeKey(communication_aes_key):
        let cipher_text = aes.encryptCBC(communication_aes_iv, plain_text)
        return cipher_text

proc decrypt_cbc(cipher_text: string): string =
    var aes = initAES()
    if aes.setDecodeKey(communication_aes_key):
        let plain_text = aes.decryptCBC(communication_aes_iv, cipher_text)
        return plain_text

let encrypted = encrypt_cbc("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
let decrypted = decrypt_cbc(encrypted)
echo decrypted
```

Thanks in advance :)

![image](https://user-images.githubusercontent.com/32266629/183153209-84848000-2792-46d3-9c15-cc1e7327b61c.png)

**Comment by jangko** [comment]
This is a common pitfall using this, and many CBC library out there. They secretly altering the value of `iv` during encryption. `let` cannot prevent the internal algorithm to modify it. The compiler can be easily fooled by pointer/ref. we humans too.

You can imagine `iv` as a counter/accumulator, the algorithm will perform calculation and then store something into `iv` for the calculation of next block of input.

It is required for both parties exchanging secret message to have both key and unmodified `iv` each time they encrypt or decrypt message. Or use modified iv for consecutive encrypt/decrypt sequence.

**Comment by itaymigdal** [comment]
Thanks for the response
