### ISSUE TITLE
"cryptCTR" yields a wrong result if parameter "nc_of" is not zero

### ISSUE THREAD

**Issue by lscrd** [jangko/nimAES#4]
For cryptCTR, if "nc_of" is not zero, as "stream_block" is initialized with zeroes, the beginning of the text is not encrypted.

Here is a small program which shows the error.

```Nim
import nimAES
var cipher = initAES()
let key = "abcdefghijklmnop"
discard cipher.setEncodeKey(key)

let text = "Some text to show that there is an error."
echo "Text -> ", text

var offset: int = 0
var nonce = "0123456701234567"
var encrypted = cipher.cryptCTR(offset, nonce, text[0..20])
encrypted &= cipher.cryptCTR(offset, nonce, text[21..text.high])
echo "Encrypted -> ", encrypted
offset = 0
nonce = "0123456701234567"
var decrypted = cipher.cryptCTR(offset, nonce, encrypted)
echo "Decrypted -> ", decrypted
```

To solve the issue, it will be necessary to initialize "stream_block" with the last encrypted value of
the nonce, so, probably, to keep it in the context.

Note that there is no such problem with CFB128 mode as the offset is applied on the IV itself.

**Comment by jangko** [comment]
it should be fixed now, thank you.

**Comment by lscrd** [comment]
Yes, it works. Thanks.
