### ISSUE TITLE
value out of range: 2298651006 notin -2147483648 .. 2147483647

### ISSUE THREAD

**Issue by Techno-Fox** [jangko/nimAES#6]
This error seems to occure with new nim 1.2.0 everytime I try to use setDecodeKey

Specifics : 
filename = 0x56667a5c"/home/kittytechno/.nimble/pkgs/nimAES-0.1.2/nimAES.nim"], [procname = 0x56667aa0"setEncodeKey",
line = 184,
filename = 0x56667a5c"/home/kittytechno/.nimble/pkgs/nimAES-0.1.2/nimAES.nim"], [procname = 0x56662060"sysFatal",
line = 49,
filename = 0x56662069"/home/kittytechno/.choosenim/toolchains/nim-1.2.0/lib/system/fatal.nim"], [procname = nil,
line = -10,

**Comment by jangko** [comment]
code example please.

**Comment by jangko** [comment]
fixed by #7, closing.

**Comment by Techno-Fox** [comment]
import nimAES
import strutils

proc encrypt*(msg: string): string =

    var input = msg
    var aes = initAES()
    let key = "T9W1HPR34JHWPEOJVN9TJWDGS3O1581R"
    var finput = ""
    #let key = "FEDCBA9876543210"
    if aes.setEncodeKey(key) != true:
        echo "[DEBUG](utils)(encrypt) Couldn't set encode key"
        quit(-1)
    if input.len() < 16:
        while input.len() != 16:
            input.add(" ")
    if input.len > 16:
        var remainder = input.len %% 16
        if remainder != 0:
            finput = input[input.len - remainder .. input.len - 1]
            input.delete(input.len - remainder, input.len - 1)

    var ivs = repeat(chr(1), 16)
    var iv = cstring(ivs)
    var encrypted = aes.encryptCBC(iv ,input)
    # echo finput
    if finput.len != 0 and finput != "":
        if finput.len() < 16:
            while finput.len() != 16:
                finput.add(" ")

        encrypted.add(aes.encryptECB(finput))

    # echo "Len : ", encrypted.len
    return encrypted.toHex()

proc decrypt*(msg: string): string =

    var input = msg
    # var input = readLine(stdin)
    var aes = initAES()
    let key = "T9W1HPR34JHWPEOJVN9TJWDGS3O1581R"

    if aes.setDecodeKey(key) != true:
        echo "[DEBUG](utils)(decrypt) Couldn't set decode key"
        quit(-1)
    # var input = readLine(stdin)
    # input.stripLineEnd()
    input = parseHexStr(input)
    # echo "input len : ", input.len
    # echo input
    var ivs = repeat(chr(1), 16)
    var iv = cstring(ivs)
    # var ivs = repeat(chr(1), 16)
    # var iv = string(ivs)
    var out2 = aes.decryptCBC(iv, input)
    out2.stripLineEnd()
    var out3 = out2.strip()
    return out3

**Comment by Techno-Fox** [comment]
Note that this algorithem worked on nim 1.0.6. Nim 1.2.0, however, gives the error.

**Comment by jangko** [comment]
it should works now with recent fix
